FROM node:20-alpine
WORKDIR /app

COPY package*.json ./
COPY packages/ ./packages/
COPY apps/backend/ ./apps/backend/

RUN npm install
RUN npm run build --workspace=@financesarthi/backend

EXPOSE 5000
CMD ["npm", "--prefix", "apps/backend", "start"]
